/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/buy/[entryId]': RouteRecordInfo<'/buy/[entryId]', '/buy/:entryId', { entryId: ParamValue<true> }, { entryId: ParamValue<false> }>,
    '/details/[type]/[id]': RouteRecordInfo<'/details/[type]/[id]', '/details/:type/:id', { type: ParamValue<true>, id: ParamValue<true> }, { type: ParamValue<false>, id: ParamValue<false> }>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/reports': RouteRecordInfo<'/reports', '/reports', Record<never, never>, Record<never, never>>,
    '/tickets': RouteRecordInfo<'/tickets', '/tickets', Record<never, never>, Record<never, never>>,
    '/timetable/': RouteRecordInfo<'/timetable/', '/timetable', Record<never, never>, Record<never, never>>,
    '/timetable/[id]': RouteRecordInfo<'/timetable/[id]', '/timetable/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/admin.vue': {
      routes: '/admin'
      views: never
    }
    'src/pages/buy/[entryId].vue': {
      routes: '/buy/[entryId]'
      views: never
    }
    'src/pages/details/[type]/[id].vue': {
      routes: '/details/[type]/[id]'
      views: never
    }
    'src/pages/home.vue': {
      routes: '/home'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/register.vue': {
      routes: '/register'
      views: never
    }
    'src/pages/reports.vue': {
      routes: '/reports'
      views: never
    }
    'src/pages/tickets.vue': {
      routes: '/tickets'
      views: never
    }
    'src/pages/timetable/index.vue': {
      routes: '/timetable/'
      views: never
    }
    'src/pages/timetable/[id].vue': {
      routes: '/timetable/[id]'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
